Fix missing logger param
Home assistant complained witht eh following error:

```
Error while setting up gogreenenergy platform for sensor: DataUpdateCoordinator.__init__() missing 1 required positional argument: 'logger'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/gogreenenergy/sensor.py", line 13, in async_setup_platform
    coordinator = DataUpdateCoordinator(
        hass,
    ...<2 lines>...
        update_interval=timedelta(hours=1),  # Update every hour
    )
TypeError: DataUpdateCoordinator.__init__() missing 1 required positional argument: 'logger'

```